sudo: false
language: python
python:
  - "2.7"
branches:
  only: 
    - master
env:
  global:
    - GH_REF: github.com/otamachan/slide-sphinxcontrib-ros.git
    - secure: "kam7M8MOuoIhKuNT0tiWviMyQbFRW7m+xBBmIhLsppnG9W8ajsLV0OwB3S6d1FJB9+VI5fJMXEcmqa+XSpyvCxlqynq8/z4RdJMVoijKgAPfNZMq0fGkKpCxl1XZ/s710e4g5vHd0vjsAchcOy/OoyqN5QUnRvzDuIi4LeYrwmKFdmgUunvghpUxmZE5bhYHaYnt+sxmZhCgklKdCLtUHPGv0Bov9IzhgryHqFi+1HBiMIK8zHvxEAKS4jFDaeNSs1yijb8w2JZ0LA6VN7o8TwhI2RYyDdiXuoeGhS5aELF65UyeE3oCvhGcVdicCTda0UBE8CD9+L2hKnTMLk+2jsxugtKqb1sqzQWr+q9g+somJDnWd0+Q+yEO6UrSvr0MJzX13aNFs80cTJxv9iyva8ecfhy/IubenfKougKpVTKDWdksC4zWf8yG4SRBB1vcRBBPL33GBvCv2cW+NgNcSmQWvO6CkcLa7mtu3BOO9Wbp0SIJ8rcWzv+5ONrK1ix9eZSpupAAQ4G/rUjCd6aMuBA0NGp5ZdR/sxuoUgtPp3pYvifFC92FbXTJUk4ZkdfzQ06g9nGLkIgXI9XGQjmMNG+3hnTBDsi2KSEXolIzSX9EbkwNlH3R82oq3CPXqylfbpobUAvqFFn5iq1RI1e9xgTehiqJ6rgXzIHsOhbqbi0="
install:
  - pip install -q -r requirements.txt
  - pip install git+https://github.com/otamachan/sphinxcontrib-ros.git
script:
  - make
after_success:
  - cd _build/slides
  - git init
  - git config user.name "Travis CI"
  - git config user.email "otamachan@gmail.com"
  - touch .nojekyll
  - git add .
  - git commit -m "Deploy to GitHub Pages"
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:gh-pages > /dev/null 2>&1